// <auto-generated />
using BloggingAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BloggingAPI.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20200117103157_UserMigration")]
    partial class UserMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BloggingAPI.Model.Blogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("blogContent")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("userId")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("id");

                    b.ToTable("blogs");
                });

            modelBuilder.Entity("BloggingAPI.Model.Comments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("blogId")
                        .HasColumnName("blogId");

                    b.Property<string>("commentContent")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("userId")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("id");

                    b.HasIndex("blogId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BloggingAPI.Model.UserDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("password")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("username")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("BloggingAPI.Model.Comments", b =>
                {
                    b.HasOne("BloggingAPI.Model.Blogs", "blogs")
                        .WithMany("comments")
                        .HasForeignKey("blogId")
                        .HasConstraintName("FK__Comments__BlogId__01142BA1");
                });
#pragma warning restore 612, 618
        }
    }
}
